__include__: [
  '../runtime.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 2
remap_mscoco_category: False

output_dir: ./output/rtdetr_r50vd_layer_prediction

PResNet:
  input_channels: 4
  pretrained: False

RTDETRTransformer:
  num_classes: 2

SetCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_layer: 1.0}
  losses: ['vfl', 'boxes', 'layers']

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoLayerOrderDataset
    img_folder: /tmp2/b12902041/Gino/preprocessed_data/images/train
    ann_file: /tmp2/b12902041/Gino/preprocessed_data/annotations/train.json
    depth_map_dir: /tmp2/b12902041/Gino/preprocessed_data/depths/train
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640], antialias: True}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: True
  batch_size: 1
  num_workers: 0
  collate_fn: default_collate_fn

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoLayerOrderDataset
    img_folder: /tmp2/b12902041/Gino/preprocessed_data/images/val
    ann_file: /tmp2/b12902041/Gino/preprocessed_data/annotations/val.json
    depth_map_dir: /tmp2/b12902041/Gino/preprocessed_data/depths/val
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640], antialias: True}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: False
  batch_size: 1
  num_workers: 0
  collate_fn: default_collate_fn

