__include__: [
  '../runtime.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

task: detection
epoches: 100

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 1
remap_mscoco_category: False

output_dir: ./output/fixed_version

PResNet:
  input_channels: 4
  pretrained: False

RTDETRTransformer:
  num_classes: 1

SetCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_layer: 1.0}
  losses: ['vfl', 'boxes', 'layers']

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoLayerOrderDataset
    img_folder: /tmp2/b12902041/Gino/preprocessed_data/images/train
    ann_file: /tmp2/b12902041/Gino/preprocessed_data/annotations/train.json
    depth_map_dir: /tmp2/b12902041/Gino/preprocessed_data/depths/train
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: RandomHorizontalFlip, p: 0.5}
        - {type: RandomDepthErasing, p: 0.5, scale: [0.02, 0.2]}
        - {type: GaussianBlur, kernel_size: [3, 3], sigma: [0.1, 2.0]}
        - {type: RandomIoUCrop, min_scale: 0.3, max_scale: 1.0, min_aspect_ratio: 0.5, max_aspect_ratio: 2.0}
        - {type: SanitizeBoundingBox, min_size: 1.0}
        - {type: Resize, size: [640, 640], antialias: True}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: True
  batch_size: 8
  num_workers: 0
  collate_fn: default_collate_fn

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoLayerOrderDataset
    img_folder: /tmp2/b12902041/Gino/preprocessed_data/images/val
    ann_file: /tmp2/b12902041/Gino/preprocessed_data/annotations/val.json
    depth_map_dir: /tmp2/b12902041/Gino/preprocessed_data/depths/val
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640], antialias: True}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: False
  batch_size: 4
  num_workers: 0
  collate_fn: default_collate_fn

